[package]
name = "unart"
version = "0.1.0"
authors = ["autondesigner <auton.designer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
rand = "0.8.0"
palette = "0.5.0"
